spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/diancan?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  context-path: /sell
#  jackson:
#    default-property-inclusion: non_null
#  redis:
#    host: 192.168.30.113
#    port: 6379

wechat:
  mpAppId: wx514922bffbab142f
  mpAppSecret: 4cf6bb876c84dd8e51e4838e17f28131

projectUrl:
  wechatMpAuthorize: http://sell.natapp4.cc
  wechatOpenAuthorize: http://sell.natapp4.cc
  sell: http://sell.natapp4.cc
