spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/diancan?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  context-path: /sell
#  jackson:
#    default-property-inclusion: non_null
#  redis:
#    host: 192.168.30.113
#    port: 6379

wechat:
  mpAppId: wx514922bffbab142f
  mpAppSecret: 4cf6bb876c84dd8e51e4838e17f28131


#wechat:
#  mpAppId: wxd898fcb01713c658
#  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
#  openAppId: wx6ad144e54af67d87
#  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
#  mchId: 1409146202
#  mchKey: c976503d34ca432c601361f969fd8d85
#  keyPath: /var/weixin_cert/h5.p12
#  notifyUrl: http://guxiangfly.nat300.top
#  templateId:
#    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://sell.natapp4.cc
  wechatOpenAuthorize: http://sell.natapp4.cc
  sell: http://sell.natapp4.cc
